language: cpp
sudo: required
cache:
  directories:
    - $HOME/omnetpp-5.2.1.tgz
before_install:
  - wget --no-check-certificate https://omnetpp.org/omnetpp/send/30-omnet-releases/2321-omnetpp-5-2-1-linux --referer=https://omnetpp.org/omnetpp -O $HOME/omnetpp-5.2.1.tgz --progress=dot:giga
  - tar xf $HOME/omnetpp-5.2.1.tgz && rm $HOME/omnetpp-5.2.1.tgz
  - cd $HOME/omnetpp-5.2.1 && ls -lah
  - echo "CFLAGS_RELEASE='-O3 -DNDEBUG=1 -D_XOPEN_SOURCE'" >> configure.user && echo "CXXFLAGS='-std=c++14'" >> configure.user && sed -i 's/PREFER_CLANG=yes/PREFER_CLANG=no/g' configure.user
  - export PATH=$HOME/omnetpp-5.2.1/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/omnetpp-5.2.1/lib:$LD_LIBRARY_PATH
  - $HOME/omnetpp-5.2.1/configure WITH_TKENV=no WITH_QTENV=no WITH_OSG=no WITH_OSGEARTH=no && make -j $(nproc) MODE=release VERBOSE=1
script: make
