language: cpp
sudo: required
addons:
  apt:
    config:
      retries: true
    packages:
      - g++-5
cache:
  directories:
    - $HOME/deps
before_install:
  - wget --no-check-certificate https://www.omnetpp.org/omnetpp/send/30-omnet-releases/2327-omnetpp-5-3-core --referer=https://omnetpp.org/omnetpp -O $HOME/deps/omnetpp-5.3-core.tgz --progress=dot:giga
  - tar xf $HOME/deps/omnetpp-5.3-core.tgz -C $HOME
  - cd $HOME/omnetpp-5.3 && ls -lah
  - echo "CFLAGS_RELEASE='-O3 -DNDEBUG=1 -D_XOPEN_SOURCE'" >> configure.user && echo "CXXFLAGS='-std=c++14'" >> configure.user && sed -i 's/PREFER_CLANG=yes/PREFER_CLANG=no/g' configure.user
  - export PATH=$HOME/omnetpp-5.3/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/omnetpp-5.3/lib:$LD_LIBRARY_PATH
  - ./configure WITH_TKENV=no WITH_QTENV=no WITH_OSG=no WITH_OSGEARTH=no && make -j $(nproc) MODE=release VERBOSE=1
  - cd -
script: make
