//
// Generated file, do not edit! Created by nedtool 5.3 from messages/QueueControl.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __QUEUECONTROL_M_H
#define __QUEUECONTROL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/QueueControl.msg:16</tt> by nedtool.
 * <pre>
 * message QueueControl
 * {
 *     int dequeue;
 * }
 * </pre>
 */
class QueueControl : public ::omnetpp::cMessage
{
  protected:
    int dequeue;

  private:
    void copy(const QueueControl& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QueueControl&);

  public:
    QueueControl(const char *name=nullptr, short kind=0);
    QueueControl(const QueueControl& other);
    virtual ~QueueControl();
    QueueControl& operator=(const QueueControl& other);
    virtual QueueControl *dup() const override {return new QueueControl(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getDequeue() const;
    virtual void setDequeue(int dequeue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QueueControl& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QueueControl& obj) {obj.parsimUnpack(b);}


#endif // ifndef __QUEUECONTROL_M_H

